[tool.poetry]
name = "ad-optimization"
version = "0.1.0"
description = ""
authors = ["Nikolas Schriefer <info@nikolasschriefer.de>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
flask-sqlalchemy = "^2.4.4"
flask-migrate = "^2.5.3"
flask-script = "^2.0.6"
flask-restx = "^0.2.0"
psycopg2-binary = "^2.8.5"
zappa = "^0.52.0"
pandas = "^1.2.0"
scipy = "^1.5.2"
matplotlib = "^3.3.1"
sentry-sdk = {version = "^0.20.3", extras = ["flask", "sqlalchemy"]}
# facebook_business = "^8.0.2"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.15.0"
flake8 = "^3.8.3"
coverage = "^5.1"
black = "^20.8b1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
